coredns:
  replicaCount: 2
  priorityClassName: system-cluster-critical
  k8sAppLabelOverride: kube-dns
  nodeSelector: {}
  tolerations: []
  podDisruptionBudget: {}
  hpa: {}
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    name: kube-dns
  deployment:
    name: coredns

  # autoscaler: {}
