nodeSelector:
  cloud.google.com/gke-container-runtime: containerd

tolerations:
- key: pool-type
  operator: Equal
  value: infra
  effect: NoSchedule

autoscaler:
  nodeSelector:
    cloud.google.com/gke-container-runtime: containerd

  tolerations:
  - key: pool-type
    operator: Equal
    value: infra
    effect: NoSchedule
